name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '18'

  registry-url:
    description: Registry to configure for publish

  install-dependencies:
    description: 'Run `pnpm install`'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm ${{ inputs.pnpm-version }}'
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0

    - name: 'Install Node.js ${{ inputs.node-version }}'
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: 'Install dependencies'
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
